Added exti interrupt pin configuration for PA15
elheck/Squiddrone pull request #323
Opened 2021-05-30 12:34 UTC by elheck

Closes #322 

No unittests written, because it is just some generated code that has been additionally generated.

It is generated by CubeMX in order to enable a external interrupt at gpio PA15, which is used by the com module

2021-05-31 18:56 UTC, c0nwild requested changes
Just some small issues. Thanks for doing this so quickly!

2021-05-31 18:56 UTC, c0nwild commented on src/mcu_config/gpio_config.c
> +  /*Configure GPIO pin : PA15 */
We already have a Pin definition for the COM EXTI pin. Please remove.

2021-05-31 18:56 UTC, c0nwild commented on src/mcu_config/gpio_config.c
> +  /*Configure GPIO pin : PA15 */
While we´re at it: Please change Mode to GPIO_MODE_IT_FALLING and Pull to GPIO_PULLUP. Thx :)

2021-06-03 12:11 UTC, elheck commented on src/mcu_config/gpio_config.c
> +  /*Configure GPIO pin : PA15 */
Fixed redundant Pin definition.

2021-06-03 12:14 UTC, elheck commented on src/mcu_config/gpio_config.c
> +  /*Configure GPIO pin : PA15 */
Fixed gpio config

2021-06-03 18:23 UTC, c0nwild approved these changes
LGTM

2021-06-03 18:23 UTC, merged