Dev motordriver
elheck/Squiddrone pull request #342
Opened 2022-01-09 15:23 UTC by elheck

Closes #130 
* Adds the motordriver to easily use the motors based on abstractions for the concrete motors and ESC's.

* Adds SVG file for the microcontroller that you can write your own vscode debugging configuration [like this](https://github.com/Squiddrone/Squiddrone/wiki/Debug-on-target#method-2-vscode-cortex-debug-plugin).

* Used formatter for some core files.

* Made unittests and did a systemstest. See the following [video](https://user-images.githubusercontent.com/42242163/148688403-6299468f-8d81-4eea-9ab8-f3e4f2297031.mp4)

2022-01-10 14:35 UTC, c0nwild commented
We must be careful not to restore timer3 by accident. Otherwise COM will not work properly.

2022-01-10 20:09 UTC, c0nwild requested changes

2022-01-10 20:09 UTC, c0nwild commented on src/propulsion/abstract_motor_driver.hpp
> +  virtual auto GetMotorSpeed(const MotorPosition which_motor) const noexcept -> std::pair<float, types::DriverStatus> = 0;
Your return value is pair<some_type, types::DriverStatus>. In the IMU and COM implmentation paired return values are in the order pair<types::DriverStatus, some_type>. Should we have a convention there?

2022-01-10 20:09 UTC, c0nwild commented on src/propulsion/abstract_motor_driver.hpp
> +class AbstractMotorDriver {
I can not find this class in the propulsion class diagram.

2022-01-10 20:09 UTC, c0nwild commented on src/propulsion/motor_driver.cpp
> +  const float min_speed = 0.0;
Also constexpr like in the function below?

2022-01-10 20:09 UTC, c0nwild commented on src/propulsion/motor_driver.cpp
> +  const float max_speed = 100.0;
Also constexpr like in the function below?

2022-01-10 20:09 UTC, c0nwild commented on src/propulsion/motor_driver.cpp
> +  if (speed < minimum_speed_in_percent or speed > maximum_speed_in_percent) {
Funny, I did not know 'or' would work. If statement in function above uses '||'. Maybe it would improve readability to keep the style consistent?

2022-01-10 20:09 UTC, c0nwild commented on src/main.cpp
> +#define SYSTEM_TEST_PROPULSION true
Please set to false.

2022-01-11 05:48 UTC, elheck commented
> 

I will forward integrate this branch to make sure that the timer stays out and all conflicts are resolved

2022-01-15 15:58 UTC, elheck commented on src/main.cpp
> +#define SYSTEM_TEST_PROPULSION true
Done

2022-01-15 16:02 UTC, elheck commented on src/propulsion/motor_driver.cpp
> +  if (speed < minimum_speed_in_percent or speed > maximum_speed_in_percent) {
You are right. Done

2022-01-15 16:03 UTC, elheck commented on src/propulsion/motor_driver.cpp
> +  const float max_speed = 100.0;
Correct. Done

2022-01-15 16:03 UTC, elheck commented on src/propulsion/motor_driver.cpp
> +  const float min_speed = 0.0;
Done

2022-01-15 16:35 UTC, elheck commented on src/propulsion/abstract_motor_driver.hpp
> +  virtual auto GetMotorSpeed(const MotorPosition which_motor) const noexcept -> std::pair<float, types::DriverStatus> = 0;
You are right. I changed it

2022-01-15 16:35 UTC, elheck commented on src/propulsion/abstract_motor_driver.hpp
> +class AbstractMotorDriver {
Updated model

2022-01-15 16:35 UTC, elheck commented on src/main.cpp
> +#define SYSTEM_TEST_PROPULSION true
Done

2022-01-15 16:35 UTC, elheck commented on src/propulsion/motor_driver.cpp
> +  if (speed < minimum_speed_in_percent or speed > maximum_speed_in_percent) {
You are right. Done

2022-01-15 16:36 UTC, elheck commented on src/propulsion/motor_driver.cpp
> +  const float max_speed = 100.0;
Done

2022-01-17 12:37 UTC, c0nwild approved these changes
Very nice. LGTM. Thx!

2022-01-17 12:38 UTC, merged